version: "3"

services:
  redis:
    container_name: redis
    image: redis:7.0.5-alpine
    command:
      - 'redis-server'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory 6gb'
      - '--maxmemory-policy allkeys-lru'
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      loki:
        aliases:
          - redis

  loki:
    image: grafana/loki:2.3.0
    depends_on:
      - cassandra
      - redis
    volumes:
      - /etc/docker-compose/local-config.yaml:/etc/loki/local-config.yaml
      - loki:/loki
    ports:
      - "3100:3100"
    restart: always
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      loki:
        aliases:
          - loki

  cassandra:
    image: bitnami/cassandra:3.11.11
    volumes:
      - cassandra:/bitnami
    restart: always
    environment:
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
      CASSANDRA_CLUSTER_NAME: loki
      CASSANDRA_DATACENTER: dc1
    networks:
      loki:
        aliases:
          - cassandra

volumes:
  cassandra:
  loki:
  redis_data:

networks:
  loki:
    driver: bridge