auth_enabled: false

server:
  http_listen_port: 3100
  http_server_read_timeout: 180s
  http_server_write_timeout: 180s

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled

schema_config:
  configs:
    - from: 2021-08-19
      store: cassandra
      object_store: filesystem
      schema: v11
      index:
        prefix: cassandra_table
        period: 24h

storage_config:
  cassandra:
    username: cassandra
    password: cassandra
    addresses: cassandra
    consistency: ONE
    auth: true
    keyspace: loki
  filesystem:
    directory: /loki/chunks
  index_queries_cache_config:
    redis:
      endpoint: redis:6379
      expiration: 1h

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 500
  ingestion_burst_size_mb: 500
  max_cache_freshness_per_query: '10m'
  max_query_series: 100000
  max_query_parallelism: 16

chunk_store_config:
  max_look_back_period: 720h

table_manager:
  retention_deletes_enabled: true
  retention_period: 720h

query_range:
  # make queries more cache-able by aligning them with their step intervals
  align_queries_with_step: true
  max_retries: 10
  # parallelize queries in 15min intervals
  split_queries_by_interval: 60m
  cache_results: true
  parallelise_shardable_queries: true
  results_cache:
    cache:
      redis:
        endpoint: "redis:6379"
        expiration: 30m

frontend:
  log_queries_longer_than: 5s
  downstream_url: http://0.0.0.0:3100
  compress_responses: true

querier:
  engine:
    # Must be a multiple of schema_config index.period
    # Default to 400 days retention.
    max_look_back_period: 720h
  query_ingesters_within: 2h
  query_timeout: 1200s
